config {
  type: "table",
  schema: "presentation_iveco",
  name: "pst_fault",
  tags: ["daily"]
}

SELECT
        description_,
        oc,
        spn,
        fmi,
        vin,
        fdt,
        fnt,
        engineSpeed,
        engineTorque,
        engineFuelTemperature,
        odometer,
        vehicleSpeed,
        geoCoordinateAltitude  ,
        geoCoordinatePositionDateTime,
        geoCoordinateLongitude,
        geoCoordinateLatitude

FROM ${ref('gld_fault')}