config {
  type: "incremental",
  schema: "golden_iveco",
  name: "gld_vehicle_data",
  tags: ["daily"]
}

pre_operations {
    DELETE FROM ${self()}
    WHERE vin  IN (SELECT DISTINCT vin  FROM ${ref('stg_vehicle_data')})
    AND  tripStartDateTime IN (SELECT DISTINCT  tripStartDateTime  FROM ${ref('stg_vehicle_data')})
}



SELECT
    VD.vin,
    VD.vehicleSpeedMax,
    VD.vehicleWeightValueAtStart,
    VD.tripStartDateTime,
    VD.tripEndDateTime,
    VD.occurrenceAEBS,
    VD.fin,
    VD.tripId,
    VD.durationCruiseControl,
    VD.vehicleLoad,
    VD.occurrenceEBS ,
    VD.occurrenceBrakePedalDriving,
    VD.vehicleSpeedAvg,
    VD.distanceDrivingWithoutTorque,
    VD.distanceCruiseControl,
    VD.accTime,
    VD.durationDriving ,
    VD.durationIdling ,
    VD.durationPTOIdling,
    VD.ptoTimeEnd ,
    VD.vehicleWeightValueAtEnd,        
    VD.totalEngineHours,
    VD.distanceBrakePedalDriving,
    VD.odometerStart,
    VD.odometerEnd,
    VD.durationPTODriving,
    VD.safetyAbsOccurrences,
    VD.safetyAsrBrakeOccurrences,
    VD.serviceBatteryChargeAtEnd,
    VD.serviceBatteryVoltageAtEnd,
    VD.automaticModeTime,
    NP.engineTotalHoursAtEnd

FROM ${ref('stg_vehicle_data')} VD
LEFT JOIN ${ref('stg_accumulatedDataNPDiesel')} NP
ON VD.Vin = NP.Vin
AND VD.tripStartDateTime = NP.tripStartDateTime
AND VD.tripEndDateTime = NP.tripEndDateTime