config {
  type: "incremental",
  schema: "golden_iveco",
  name: "gld_lamp",
  tags: ["daily"]
}
pre_operations {
    DELETE FROM ${self()}
    WHERE vin  IN (SELECT DISTINCT vin  FROM ${ref('stg_lamp')})
    AND  fdt IN (SELECT DISTINCT  fdt  FROM ${ref('stg_lamp')})
}



SELECT
        name_,
        status_,
        vin,
        fdt,
        fnt,
        engineSpeed,
        engineTorque,
        engineFuelTemperature,
        odometer,
        vehicleSpeed,
        geoCoordinateLatitude,
        geoCoordinateLongitude,
        geoCoordinateAltitude,
        geoCoordinatePositionDateTime,
        requestServerDateTime


FROM ${ref('stg_lamp')}