config {
  type: "incremental",
  schema: "golden_iveco",
  name: "gld_vehicle_data",
  tags: ["daily"]
}

pre_operations {
    DELETE FROM ${self()}
    WHERE vin  IN (SELECT DISTINCT vin  FROM ${ref('stg_vehicle')})
    AND  Date (tripStartDateTime) IN (SELECT DISTINCT  Date (tripStartDateTime)  FROM ${ref('stg_vehicle')})
}

SELECT
    vin,
    vehicleSpeedMax,
    vehicleWeightValueAtStart,
    tripStartDateTime,
    tripEndDateTime,
    occurrenceAEBS,
    fin,
    tripId,
    durationCruiseControl,
    vehicleLoad,
    occurrenceEBS ,
    occurrenceBrakePedalDriving,
    vehicleSpeedAvg,
    distanceDrivingWithoutTorque,
    distanceCruiseControl,
    accTime,
    durationDriving ,
    durationIdling ,
    durationPTOIdling,
    ptoTimeEnd ,
    vehicleWeightValueAtEnd,        
    totalEngineHours,
    distanceBrakePedalDriving,
    odometerStart,
    odometerEnd,
    durationPTODriving,
    safetyAbsOccurrences,
    safetyAsrBrakeOccurrences,
    serviceBatteryChargeAtEnd,
    serviceBatteryVoltageAtEnd,
    automaticModeTime

FROM ${ref('stg_vehicle_data')}